### ISSUE TITLE
Error: failed to connect to [undefined:27017]

### ISSUE THREAD

**Issue by DayOfThePenguin** [hyperstudio/MIT-Annotation-Data-Store#13]
Hi, I've been working on installing the data store, but I can't get it to run successfully with foreman; I have mongodb running on localhost (and my IP is 192.168.5.1).  If I browse to either localhost:27017 or 192.168.5.1:27017, I get the mongodb test message, so I know the server is running.  However, if I try <code>foreman start</code>, I get the following:

<code>11:19:17 web.1  | started with pid 3398
11:19:20 web.1  | connect.multipart() will be removed in connect 3.0
11:19:20 web.1  | visit https://github.com/senchalabs/connect/wiki/Connect-3.0 for alternatives
11:19:20 web.1  | connect.limit() will be removed in connect 3.0
11:19:20 web.1  | Listening on 50000
11:19:20 web.1  | 
11:19:20 web.1  | events.js:72
11:19:20 web.1  |         throw er; // Unhandled 'error' event
11:19:20 web.1  |               ^
11:19:20 web.1  | Error: failed to connect to [undefined:27017]
11:19:20 web.1  |     at null.<anonymous> (/Users/Colin/Developer/annotation/annotation-data-store/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:540:74)
11:19:20 web.1  |     at EventEmitter.emit (events.js:106:17)
11:19:20 web.1  |     at null.<anonymous> (/Users/Colin/Developer/annotation/annotation-data-store/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:140:15)
11:19:20 web.1  |     at EventEmitter.emit (events.js:98:17)
11:19:20 web.1  |     at Socket.<anonymous> (/Users/Colin/Developer/annotation/annotation-data-store/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:478:10)
11:19:20 web.1  |     at Socket.EventEmitter.emit (events.js:95:17)
11:19:20 web.1  |     at net.js:830:16
11:19:20 web.1  |     at process._tickCallback (node.js:415:13)
11:19:20 web.1  | exited with code 8
11:19:20 system | sending SIGTERM to all processes</code>

I messed around with my .env file a bit, and this is what I had at the time of the run above:
<code>NODE_ENV=development
PATH=bin:node_modules/.bin:/usr/local/bin:/usr/bin:/bin                         
PORT=50000                                                                      
SECRET=the-secret-the-annotator-gets-from-the-authorizing-site                  
CONSUMER=name-of-the-app-on-which-the-annotator-runs                            
VERSION=1.0                                                                     
LIVE_DB=mongodb://Colin:pass@192.168.1.5:12345/LIVE_DB                          
LOCAL_DB=mongodb://localhost/annotationdb                                       
STAGING_DB=mongodb://Colin:pass@192.168.1.5:12345/STAGING_DB </code>

I have annotationdb, LIVE_DB, and STAGING_DB in mongodb; both LIVE_DB and STAGING_DB have a user named Colin with password "pass."  annotationdb has no users and none of the databases actually have any documents in them (besides the user documents in LIVE_DB and STAGING_DB).  I apologize if there is something obvious I am missing here; I have limited experience with databases.

Thanks!

-Colin

**Comment by jamiefolsom** [comment]
Hi @DayOfThePenguin,

If you can post your entire .env file to a gist, and share that with me, I'd be glad to take a look.

Thanks,

Jamie

**Comment by DayOfThePenguin** [comment]
@jamiefolsom,

Thanks for the quick response; I put it <a href=https://gist.github.com/DayOfThePenguin/af3365ce7debf73e4fb5#file-gistfile1-txt>here</a>.  Again, I apologize if I missed something really obvious.

Thanks

-Colin

**Comment by jamiefolsom** [comment]
Hi, @DayOfThePenguin,

Just replied to your gist. Have a look. 

Jamie

**Comment by DayOfThePenguin** [comment]
@jamiefolsom,

Thanks!  That works.

Colin
